---
# Form running gradle locally
server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:./h2/test
    platform: h2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true



